on:
  workflow_call:
    inputs:
      after:
        required: true
        type: string
        default: 2 hours
    outputs:
      exists:
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
      - name: print latest_commit
        run: echo ${{ github.sha }}
      - id: exists
        continue-on-error: true
        name: check recent commit
        run: echo "exists=true" >> $GITHUB_OUTPUT && test -z $(git rev-list -n 1 --after="${{ inputs.after }}"  ${{ github.sha }}) && echo "exists=false" >> $GITHUB_OUTPUT
