name: Cache Nuget by OS
description: Cache Nuget Packages for current runner OS
runs:
  using: composite
  steps:
  - name: Set up nuget dependency caching for faster builds
    uses: actions/cache@v4
    with:
      path: ~/.nuget/packages
      key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      restore-keys: |
        ${{ runner.os }}-nuget-
