on:
  workflow_call:
    inputs:
      after:
        required: true
        type: string
        default: 2 hours
    outputs:
      exists:
        value: ${{ jobs.check-recent-commit.outputs.exists }}
jobs:
  check-recent-commit:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      exists: ${{ steps.check-if-exists.outputs.exists }}
    steps:
      - uses: actions/checkout@v4
      - name: print latest_commit
        run: echo ${{ github.sha }}
      - id: check-if-exists
        continue-on-error: true
        name: check recent commit
        run: echo "exists=true" >> $GITHUB_OUTPUT && test -z $(git rev-list -n 1 --after="${{ inputs.after }}"  ${{ github.sha }}) && echo "exists=false" >> $GITHUB_OUTPUT
      - run: echo "Has recent commit? ${{ steps.check-if-exists.outputs.exists }}"
